### PR TITLE
Optimise finding of existing binds when adding a bind variable

### PR DESCRIPTION
**Pull request by Page-**
Change-type: patch

### CODE REVIEW

**Comment by roman-mazur** [comment]
Is it "inspired" by performance issues with service installs?

**Comment by Page-** [comment]
Yup @roman-mazur, it was a case of a query that had a huge number of bind variables where suddenly the performance of the compare function really became noticeable, because it ones the compare function against each existing bind for each new bind added - not too bad with 10 or even 100 bind vars but definitely noticeable with 1000.  All this does is speed up that comparison function significantly in the common case so that it reduces the impact of that time complexity but it will still be a problem with enough bind vars. To handle massive numbers we'd need to change it to use a lookup table or similar instead to bring the time complexity down, but at the same time having that many bind vars by itself is a bit questionable

**Comment by roman-mazur** [comment]
Great, thanks.
And do we collect any benchmark metrics using tests in `stress.coffee`?

**Comment by Page-** [comment]
I did it manually and with `time npx mocha` for just stress.coffee it went from ~12.5s to ~4s and for my real world test case profiling it went from 15,241ms cpu time to 688ms

**Pull request merged**
