### PR TITLE
Separate src/out dirs to avoid issues with importing .ts over .d.ts

### PR DESCRIPTION
**Pull request by Page-**
Change-type: patch

### CODE REVIEW

**Comment by Page-** [comment]
@resin-ci retest

**Comment by Page-** [comment]
@resin-ci retest

**Comment by Page-** [comment]
@resin-ci retest

**Comment by Page-** [comment]
@resin-ci retest

**Comment by Page-** [comment]
@resin-ci retest

**Comment by Page-** [comment]
@resin-ci retest

**Comment by nazrhom** [comment]
@resin-ci retest

**Comment by Page-** [comment]
@resin-ci retest

**Pull request merged**
